"""Initial migration

Revision ID: a923091d0dff
Revises: 
Create Date: 2025-05-31 21:03:29.965053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a923091d0dff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Название теста'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание теста'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Имя JSON-файла с вопросами теста'),
    sa.Column('is_available', sa.Boolean(), nullable=False, comment='Доступен ли тест для прохождения'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания теста'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index(op.f('ix_tests_id'), 'tests', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='Имя пользователя'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='Фамилия пользователя'),
    sa.Column('middle_name', sa.String(length=100), nullable=False, comment='Отчество пользователя'),
    sa.Column('faculty', sa.Enum('FIB', 'FKSIS', 'FKP', 'FRE', 'IEF', 'FITU', name='facultyenum'), nullable=False, comment='Факультет пользователя'),
    sa.Column('course', sa.Enum('FIRST', 'SECOND', 'THIRD', 'FOURTH', 'FIFTH', 'SIXTH', name='courseenum'), nullable=False, comment='Курс обучения'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Хэш пароля'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания аккаунта'),
    sa.Column('completed_tests', sa.JSON(), nullable=True, comment='Список пройденных тестов с результатами'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('test_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.Column('test_id', sa.Integer(), nullable=False, comment='ID теста'),
    sa.Column('current_question_index', sa.Integer(), nullable=False, comment='Индекс текущего вопроса (начиная с 0)'),
    sa.Column('answers', sa.JSON(), nullable=True, comment='Массив ответов пользователя'),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время начала прохождения теста'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_progress_id'), 'test_progress', ['id'], unique=False)
    op.create_index(op.f('ix_test_progress_test_id'), 'test_progress', ['test_id'], unique=False)
    op.create_index(op.f('ix_test_progress_user_id'), 'test_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_progress_user_id'), table_name='test_progress')
    op.drop_index(op.f('ix_test_progress_test_id'), table_name='test_progress')
    op.drop_index(op.f('ix_test_progress_id'), table_name='test_progress')
    op.drop_table('test_progress')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tests_id'), table_name='tests')
    op.drop_table('tests')
    # ### end Alembic commands ### 