"""Remove test_progress table

Revision ID: b1a1993d67d4
Revises: a923091d0dff
Create Date: 2025-06-01 16:53:30.506160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1a1993d67d4'
down_revision = 'a923091d0dff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_progress_id', table_name='test_progress')
    op.drop_index('ix_test_progress_test_id', table_name='test_progress')
    op.drop_index('ix_test_progress_user_id', table_name='test_progress')
    op.drop_table('test_progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='ID пользователя'),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='ID теста'),
    sa.Column('current_question_index', sa.INTEGER(), autoincrement=False, nullable=False, comment='Индекс текущего вопроса (начиная с 0)'),
    sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Массив ответов пользователя'),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Дата и время начала прохождения теста'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='test_progress_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='test_progress_pkey')
    )
    op.create_index('ix_test_progress_user_id', 'test_progress', ['user_id'], unique=False)
    op.create_index('ix_test_progress_test_id', 'test_progress', ['test_id'], unique=False)
    op.create_index('ix_test_progress_id', 'test_progress', ['id'], unique=False)
    # ### end Alembic commands ### 